---

# sudo apt-get install *
- name: Installing docker packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags:
    - docker

# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- name: Add Docker's official GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

# sudo apt-key fingerprint 0EBFCD88
- name: Verifing that we have the key with the fingerprint
  become: true
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker

# sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
- name: Setting up the stable repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  tags:
    - docker

# sudo apt-get update
- name: Updating apt packages
  become: true
  apt:
    update_cache: yes
  tags:
    - docker

# sudo apt-get install docker-ce=18.03.*
- name: Installing docker
  become: true
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Start docker on boot
  tags:
    - docker

- name: Install unit file
  become: true
  copy: 
    src: docker.service 
    dest: /lib/systemd/system/ 
    owner: root 
    mode: 644
  notify:
    - reload systemd      

# sudo apt-get install docker-compose
- name: Installing docker-compose
  become: true
  apt:
    name: docker-compose
    state: present
    update_cache: yes
  tags:
    - docker

- name: flush hanlers
  meta: flush_handlers

- name: Restart service docker
  become: true
  service:
    name: docker
    state: restarted


