---
- name: Start docker on boot
  systemd:
    name: docker
    state: started
    enabled: yes

- name: reload systemd
  become: true
  command: systemctl daemon-reload    


- name: Restart service docker
  become: true
  service:
    name: docker
    state: restarted

